baseurl: "" # the subpath of your site
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Site settings
title: "Mauro Junior - Portfolio"
description: "Portfolio profissional de Mauro Junior - Desenvolvedor, Animador e Motion Designer"
language: "pt-BR"

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 6
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed