#-------------------------------
# General Site Settings
title: Mauro Junior Portfolio
logo: logo.svg # You can add own logo
description: Portfolio profissional de Mauro Junior - Desenvolvedor, Animador e Motion Designer

#-------------------------------
# Author Settings
author:
  name: Mauro Junior
  image: profile.jpg # Update this with your profile image
  say-hello: Olá, sou <strong>Mauro Junior</strong>
  bio: Desenvolvedor, Animador e Motion Designer criando experiências digitais únicas e memoráveis. Especializado em <strong>desenvolvimento web</strong>, <strong>animação</strong> e <strong>motion design</strong>.

#-------------------------------
# Contact links
github: https://github.com/Mauroetc # Add your GitHub handle
linkedin: # Add your LinkedIn handle
behance: # Add your Behance handle
vimeo: # Add your Vimeo handle
instagram: # Add your Instagram handle

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # Not needed for portfolio

#-------------------------------
# Google Analytics
google-analytics: # Add your identifier

#-------------------------------
# Navigation Menu
menu:
  - url: /about/
    name: Sobre
  - url: /animation/
    name: Animação
  - url: /programming/
    name: Programação
  - url: /video/
    name: Vídeo
  - url: /motion/
    name: Motion Design
  - url: /achievements/
    name: Conquistas
